---
title: "MA06A - Matemática 6"
output:
  html_document:
    toc: false
---

```{r setup, include=FALSE, cache=FALSE}
source("setup_knitr.R")
```

<div class="alert alert-danger" role="alert">
**ATENÇÃO!**

- Avaliação I - Dia 27/04 - 15:50h às 17:50h

- Avaliação II - Dia 29/06 - 15:50h às 17:50h

- Não haverá aula - Dias 20/04 e 04/05

- Entrega do trabalho - ùltimo dia de aula, dia 29/06

-  Avaliação final - 06/07 - 15:50h às 17:50h

</div>

# Detalhes da oferta da disciplina

- **Cursos:**
    - Turma T11
- **Período:** Primeiro semestre de 2020
- **Professor Responsável:**
    - Felipe E. Barletta Mendes, DAEST/UTFPR

- **Local e horários:**
    - Sala E-206:
        - Segundas, 15:50 - 17:50

- **Horários de atendimento do professor (preferenciais):**
    - Segundas: 18:00 as 19:00
    - Terças e quintas: 18:00 as 20:00. 
    - Outros horários podem ser agendados previamente.
- **Frequência**: de acordo com as normas da Universidade, mínimo de 75%
- **Avaliação**:
    - Duas provas, cada uma valendo 10 pontos;
    - Uma trabalho valendo 10 pontos;
        - A nota final do aluno será a média aritmética simples dos pontos das duas provas e do trabalho;
        - Haverá uma avaliação final.
    
- **Datas importantes:**
    - **02/03**: Início do curso
    - **29/06**: Final do curso
    - **06/07**: Avaliação final
    - **14/07**: Conclusão das Atividades Docentes
    - **15/07 e 16/07**: Finalização dos Diários de Classe
   
   

# Programa/objetivos da disciplina

O objetivo desta disciplina é capacitar os alunos em conceitos básicos
de estatística que permitam a interpretação de resultados de análises e
procedimentos estatísticos, bem como a execução de procedimentos e
análises estatística básicas. O curso compreende três grandes tópicos:

- Análise descritiva e exploratória de dados
- Noções de probabilidades e distribuições de probabilidades para variáveis aleatórias discreta e contínua
